create extension if not exists "pgcrypto";

create table if not exists public.instructors (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  first_name text not null,
  last_name text,
  display_name text,
  suburb text not null,
  postcode text,
  state text default 'VIC',
  phone text,
  email text,
  adi_registration text,
  licence_types text[] default array['Car'],
  transmission text,
  languages text[] default array[]::text[],
  gender text,
  hourly_rate numeric(8, 2),
  five_hour_pack_price numeric(8, 2),
  ten_hour_pack_price numeric(8, 2),
  lesson_duration_minutes integer,
  bio text,
  anxiety_friendly boolean default false,
  international_licence_conversion boolean default false,
  familiar_test_centres text[] default array[]::text[],
  service_areas text[] default array[]::text[],
  vehicle_make text,
  vehicle_model text,
  vehicle_year integer,
  vehicle_transmission text,
  dual_controls boolean default false,
  facebook_url text,
  google_business_url text,
  verified boolean default false,
  claim_status text default 'unclaimed',
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  google_place_id text,
  source_notes text,
  is_sample boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
